1 entries in records
1 entries in records
❌ Error processing record address: (psycopg2.ProgrammingError) can't adapt type 'INTEGER'
[SQL: INSERT INTO schema_lookup (table_name, column_name, data_type, is_nullable, is_primary_key, source_db) VALUES (%(table_name__0)s, %(column_name__0)s, %(data_type__0)s, %(is_nullable__0)s, %(is_primary_key__0)s, %(source_db__0)s), (%(table_name__1)s,  ... 838 characters truncated ... , %(column_name__8)s, %(data_type__8)s, %(is_nullable__8)s, %(is_primary_key__8)s, %(source_db__8)s)]
[parameters: {'table_name__0': 'address', 'column_name__0': 'AddressID', 'source_db__0': 'SQL Server', 'is_nullable__0': False, 'is_primary_key__0': True, 'data_type__0': INTEGER(), 'table_name__1': 'address', 'column_name__1': 'AddressLine1', 'source_db__1': 'SQL Server', 'is_nullable__1': False, 'is_primary_key__1': False, 'data_type__1': NVARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__2': 'address', 'column_name__2': 'AddressLine2', 'source_db__2': 'SQL Server', 'is_nullable__2': True, 'is_primary_key__2': False, 'data_type__2': NVARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__3': 'address', 'column_name__3': 'City', 'source_db__3': 'SQL Server', 'is_nullable__3': False, 'is_primary_key__3': False, 'data_type__3': NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__4': 'address', 'column_name__4': 'StateProvinceID', 'source_db__4': 'SQL Server', 'is_nullable__4': False, 'is_primary_key__4': False, 'data_type__4': INTEGER(), 'table_name__5': 'address', 'column_name__5': 'PostalCode', 'source_db__5': 'SQL Server', 'is_nullable__5': False, 'is_primary_key__5': False, 'data_type__5': NVARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__6': 'address', 'column_name__6': 'SpatialLocation', 'source_db__6': 'SQL Server', 'is_nullable__6': True, 'is_primary_key__6': False, 'data_type__6': NullType(), 'table_name__7': 'address', 'column_name__7': 'rowguid', 'source_db__7': 'SQL Server', 'is_nullable__7': False, 'is_primary_key__7': False, 'data_type__7': UNIQUEIDENTIFIER(), 'table_name__8': 'address', 'column_name__8': 'ModifiedDate', 'source_db__8': 'SQL Server', 'is_nullable__8': False, 'is_primary_key__8': False, 'data_type__8': DATETIME()}]
(Background on this error at: https://sqlalche.me/e/20/f405)
❌ Error processing record address: (psycopg2.ProgrammingError) can't adapt type 'INTEGER'
[SQL: INSERT INTO schema_lookup (table_name, column_name, data_type, is_nullable, is_primary_key, source_db) VALUES (%(table_name__0)s, %(column_name__0)s, %(data_type__0)s, %(is_nullable__0)s, %(is_primary_key__0)s, %(source_db__0)s), (%(table_name__1)s,  ... 838 characters truncated ... , %(column_name__8)s, %(data_type__8)s, %(is_nullable__8)s, %(is_primary_key__8)s, %(source_db__8)s)]
[parameters: {'table_name__0': 'address', 'column_name__0': 'AddressID', 'source_db__0': 'SQL Server', 'is_nullable__0': False, 'is_primary_key__0': True, 'data_type__0': INTEGER(), 'table_name__1': 'address', 'column_name__1': 'AddressLine1', 'source_db__1': 'SQL Server', 'is_nullable__1': False, 'is_primary_key__1': False, 'data_type__1': NVARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__2': 'address', 'column_name__2': 'AddressLine2', 'source_db__2': 'SQL Server', 'is_nullable__2': True, 'is_primary_key__2': False, 'data_type__2': NVARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__3': 'address', 'column_name__3': 'City', 'source_db__3': 'SQL Server', 'is_nullable__3': False, 'is_primary_key__3': False, 'data_type__3': NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__4': 'address', 'column_name__4': 'StateProvinceID', 'source_db__4': 'SQL Server', 'is_nullable__4': False, 'is_primary_key__4': False, 'data_type__4': INTEGER(), 'table_name__5': 'address', 'column_name__5': 'PostalCode', 'source_db__5': 'SQL Server', 'is_nullable__5': False, 'is_primary_key__5': False, 'data_type__5': NVARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), 'table_name__6': 'address', 'column_name__6': 'SpatialLocation', 'source_db__6': 'SQL Server', 'is_nullable__6': True, 'is_primary_key__6': False, 'data_type__6': NullType(), 'table_name__7': 'address', 'column_name__7': 'rowguid', 'source_db__7': 'SQL Server', 'is_nullable__7': False, 'is_primary_key__7': False, 'data_type__7': UNIQUEIDENTIFIER(), 'table_name__8': 'address', 'column_name__8': 'ModifiedDate', 'source_db__8': 'SQL Server', 'is_nullable__8': False, 'is_primary_key__8': False, 'data_type__8': DATETIME()}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Finished running source to staging in series
Finished running source to staging in series
Total time taken 1.83 seconds
Total time taken 1.83 seconds
